server:
  port: 8084

spring:
  application:
    name: frontend-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
#    circuitbreaker:
#      resilience4j:
#        enabled: false

comment-service:
#  graphql-url: http://localhost:8082/graphql
  graphql-url: http://comment-service:8082/graphql # for docker

post-service:
  grpc:
#    host: localhost
    host: post-service # for docker
    port: 9090

user-service:
#  url: http://localhost:8083/api/v1/users
  url: http://user-service:8083/api/v1/users # for docker
  auth:
#    url: http://localhost:8083/auth
    url: http://user-service:8083/auth # for docker
    username: "admin"
    password: "admin"
    requestHeader: "authorization"
